WelcomeTesttargetInstance: ${TEST_URL:http://localhost:8100}

ccdGatewayUrl: ${CCD_GW_URL:http://localhost:3453}

hmc:
  baseUrl: ${HMC_API_URL:http://127.0.0.1:4561}

idam:
  baseUrl: ${IDAM_URL:http://127.0.0.1:5000}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  scope: "openid profile authorities acr roles create-user manage-user search-user"
  system:
    username: ${IA_SYSTEM_USERNAME:ia-system-user@fake.hmcts.net}
    password: ${IA_SYSTEM_PASSWORD:something}
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IA_S2S_MICROSERVICE:ia}
    url: ${S2S_URL:http://127.0.0.1:4502}
  s2s-authorised:
    services: ${IA_S2S_AUTHORIZED_SERVICES:iac}

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000

spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_IDAM_URL:http://sidam-simulator:5000}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_SECRET:OOOOOOOOOOOOOOOO}
      resourceserver:
        jwt:
          jwk-set-uri: ${OPEN_ID_IDAM_URL:http://sidam-simulator:5000}/o/jwks

