server:
  port: 8100

management:
  endpoint:
    health:
      show-details: "always"
    status:
      http-mapping:
        UP: 200
        DOWN: 503
  endpoints:
    web:
      base-path: /

springdoc:
  packagesToScan: uk.gov.hmcts.reform.iahearingsapi.controllers

spring:
  config:
    import: "optional:configtree:/mnt/secrets/ia/"
  application:
    name: Immigration & Asylum hearings API
  jackson.date-format: yyyy-MM-dd
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_SECRET:something}
      resourceserver:
        jwt:
          jwk-set-uri: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}/o/jwks

azure:
  application-insights:
    instrumentation-key: ${ia.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
