server:
  port: ${PORT:8100}

management:
  endpoint:
    health:
      show-details: "always"
      status:
        http-mapping:
          UP: 200
          DOWN: 503
      probes:
        enabled: true
  endpoints:
    web:
      base-path: "/"

health:
  services:
    idam:
      uri: ${IDAM_URL:http://127.0.0.1:4501}/health
      response: '"status":"UP"'
    serviceAuth:
      uri: ${S2S_URL:http://127.0.0.1:4502}/health
      response: '"status":"UP"'
    hcm:
      uri: ${HMC_API_URL:http://127.0.0.1:4561}/health
      response: '"status":"UP"'

spring:
  cloud:
    bootstrap:
      enabled: true
  config:
    import: "optional:configtree:/mnt/secrets/ia/"
  application:
    name: Immigration & Asylum hearings API
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_SECRET:something}
      resourceserver:
        jwt:
          jwk-set-uri: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}/o/jwks

###Security config - add events below for access
security:
  anonymousPaths:
    - "/"
    - "/asylum/test"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/loggers/**"
    - "/swagger-ui/**"
    - "/swagger-resources/**"
    - "/v3/api-docs/**"
    - "/favicon.ico"
  authorisedRoles:
    - "caseworker-ia"
  roleEventAccess:
    citizen:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
    caseworker-ia-legalrep-solicitor:
      - "startAppeal"
      - "editAppeal"
      - "submitAppeal"
    caseworker-ia-admofficer:
      - "listCase"
      - "updateHearingRequest"
      - "recordAdjournmentDetails"
      - "endAppeal"
      - "updateInterpreterDetails"
      - "updateInterpreterBookingStatus"
    caseworker-ia-caseworker:
      - "listCase"
    caseworker-ia-caseofficer:
      - "updateHearingRequest"
      - "recordAdjournmentDetails"
      - "endAppeal"
      - "updateInterpreterDetails"
      - "updateInterpreterBookingStatus"
    caseworker-ia-respondentofficer:
    caseworker-ia-iacjudge:
    caseworker-ia-system:
      - "handleHearingException"
      - "triggerCmrUpdated"
      - "recordAdjournmentDetails"
      - "listCaseForFTOnly"
      - "triggerCmrListed"
      - "triggerReviewInterpreterBookingTask"

### dependency configuration
ccdGatewayUrl: ${CCD_GW_URL:http://localhost:3453}
core_case_data:
  api:
    url: ${CCD_URL:http://127.0.0.1:4452}

xui:
  api:
    baseUrl: ${XUI_URL:http://localhost:3002}

hearingValues:
  screenFlowJsonFilePath: ${SCREEN_FLOW_JSON_FILE_PATH:/screenFlowNoPanel.json}
  caseCategories: "BFA1-TST"
  hmctsServiceId: "BFA1"

rd-commondata:
  api:
    url: ${REF_DATA_URL:http://localhost:8991}

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        loggerLevel: full


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


#OpenID
idam:
  baseUrl: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IA_S2S_MICROSERVICE:iac}
    url: ${S2S_URL:http://127.0.0.1:4502}
  s2s-authorised:
    services: ${IA_S2S_AUTHORIZED_SERVICES:ccd,ccd_data,ccd_gw,ccd_ps,iac,xui_webapp}
  ia_system_user:
    username: ${IA_SYSTEM_USERNAME:system-user}
    password: ${IA_SYSTEM_PASSWORD:system-password}
    scope: "openid profile authorities acr roles create-user manage-user search-user"

#HMC
hmc:
  baseUrl: ${HMC_API_URL:http://127.0.0.1:4561}

prof.ref.data.url: ${PROF_REF_DATA_URL:http://localhost:8991}
prof.ref.data.path.org.users: ${PROF_REF_DATA_ORG_USERS_PATH:/refdata/external/v1/organisations/users}
prof.ref.data.path.org.organisation: ${PROF_REF_DATA_ORG_ORGANISATION_PATH:/refdata/external/v1/organisations}

featureFlag:
  exampleFeatureFlag: ${EXAMPLE_FEATURE_FLAG:true}

launchDarkly:
  sdkKey: ${LAUNCH_DARKLY_SDK_KEY:sdk-key}
  connectionTimeout: 5000
  socketTimeout: 5000

core_case_data_api_assignments_url: ${CCD_URL:http://127.0.0.1:4452}
assign_case_access_api_url: ${AAC_URL:http://127.0.0.1:4454}
core_case_data_api_assignments_path: "/case-users"
assign_case_access_api_assignments_path: "/case-assignments"

ia:
  config:
    validator:
      secret: ${IA_CONFIG_VALIDATOR_SECRET:}
  hmctsServiceId: ${HMCTS_SERVICE_ID:BFA1}

govUkHolidays:
  url: https://www.gov.uk/

azure:
  service-bus:
    connection-postfix: ${HMC_RESPONSE_TOPIC_CONNECTION_POSTFIX:.servicebus.windows.net}
    hmc-to-hearings-api:
      namespace: ${HMC_HEARINGS_TOPIC_NAMESPACE:hmc-servicebus-demo}
      topicName: ${HMC_HEARINGS_TOPIC_NAME:}
      subscriptionName: ${HMC_HEARINGS_TOPIC_SUBSCRIPTION_NAME:}
      receiveTimeout: ${HMC_HEARINGS_TOPIC_RECEIVE_TIMEOUT:1}
      idleTimeout: ${HMC_HEARINGS_TOPIC_IDLE_TIMEOUT:3600000}
      username: ${HMC_HEARINGS_TOPIC_POLICY_NAME:}
      password: ${HMC_HEARINGS_TOPIC_ACCESS_KEY:}

iaCaseApi:
  url: ${IA_CASE_API_URL:http://127.0.0.1:8090}
  aboutToStartPath: "/asylum/ccdAboutToStart"
  aboutToSubmitPath: "/asylum/ccdAboutToSubmit"
  midEventPath: "/asylum/ccdMidEvent"
  ccdSubmittedPath: "/asylum/ccdSubmitted"

bail:
  hearingValues:
    caseCategories: "BFA1-BLS"

flags:
  hmc-to-hearings-api:
    enabled: ${HMC_HEARINGS_LISTENING_ENABLED:true}
