server:
  port: ${PORT:8100}

management:
  endpoint:
    health:
      show-details: "always"
      status:
        http-mapping:
          UP: 200
          DOWN: 503
  endpoints:
    web:
      base-path: "/"
  health:
    probes:
      enabled: true
  services:
    idam:
      uri: ${IDAM_URL:http://127.0.0.1:4501}/health
      response: '"status":"UP"'
    documentsApi:
      uri: ${IA_CASE_DOCUMENTS_API_URL:http://127.0.0.1:8092}/health
      response: '"status":"UP"'
    notificationApi:
      uri: ${IA_CASE_NOTIFICATIONS_API_URL:http://127.0.0.1:8093}/health
      response: '"status":"UP"'
    serviceAuth:
      uri: ${S2S_URL:http://127.0.0.1:4502}/health
      response: '"status":"UP"'

spring:
  config:
    import: "optional:configtree:/mnt/secrets/ia/"
  application:
    name: Immigration & Asylum hearings API
  jackson.date-format: yyyy-MM-dd
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_SECRET:something}
      resourceserver:
        jwt:
          jwk-set-uri: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}/o/jwks

### dependency configuration
ccdGatewayUrl: ${CCD_GW_URL:http://localhost:3453}
core_case_data_api_url: ${CCD_URL:http://127.0.0.1:4452}
document_management.url: ${DM_URL:http://127.0.0.1:4506}


documentsApi:
  endpoint: ${IA_CASE_DOCUMENTS_API_URL:http://127.0.0.1:8092}
  aboutToSubmitPath: "/bail/ccdAboutToSubmit"
  aboutToStartPath: "/bail/ccdAboutToStart"

notificationsApi:
  endpoint: ${IA_CASE_NOTIFICATIONS_API_URL:http://127.0.0.1:8093}
  aboutToSubmitPath: "/bail/ccdAboutToSubmit"
  ccdSubmittedPath: "/bail/ccdSubmitted"


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


#OpenID
idam:
  baseUrl: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IA_S2S_MICROSERVICE:ia}
    url: ${S2S_URL:http://127.0.0.1:4502}
  s2s-authorised:
    services: ${IA_S2S_AUTHORIZED_SERVICES:ccd,ccd_data,ccd_gw,ccd_ps,iac}
  ia_system_user:
    username: ${IA_SYSTEM_USERNAME:system-user}
    password: ${IA_SYSTEM_PASSWORD:system-password}
    scope: "openid profile authorities acr roles create-user manage-user search-user"

prof.ref.data.url: ${PROF_REF_DATA_URL:http://localhost:8991}
prof.ref.data.path.org.users: ${PROF_REF_DATA_ORG_USERS_PATH:/refdata/external/v1/organisations/users}
prof.ref.data.path.org.organisation: ${PROF_REF_DATA_ORG_ORGANISATION_PATH:/refdata/external/v1/organisations}

featureFlag:
  isDocumentGenerationEnabled: ${IA_DOCUMENT_GENERATION_ENABLED:true}

launchDarkly:
  sdkKey: ${LAUNCH_DARKLY_SDK_KEY:sdk-key}
  connectionTimeout: 5000
  socketTimeout: 5000

azure:
  application-insights:
    instrumentation-key: ${ia.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
