---
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ia:
      secrets:
        - name: docmosis-enabled
          alias: IA_DOCMOSIS_ENABLED
        - name: em-stitching-enabled
          alias: IA_EM_STITCHING_ENABLED
        - name: system-username
          alias: IA_SYSTEM_USERNAME
        - name: system-password
          alias: IA_SYSTEM_PASSWORD
        - name: idam-client-id
          alias: IA_IDAM_CLIENT_ID
        - name: idam-secret
          alias: IA_IDAM_SECRET
        - name: s2s-secret
          alias: IA_S2S_SECRET
        - name: s2s-microservice
          alias: IA_S2S_MICROSERVICE
        - name: prof-ref-data-url
          alias: PROF_REF_DATA_URL
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - ia-config-validator-secret
        - app-insights-connection-string
