java:
  image: 'hmctspublic.azurecr.io/ia/hearings-api:latest'
  applicationPort: 8100
  readinessPath: '/health/readiness'
  aadIdentityName: ia
  ingressHost: ia-hearings-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    CCD_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    AAC_URL: "http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_GW_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DM_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IA_IDAM_REDIRECT_URI: "https://ia-hearings-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    PROF_REF_DATA_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    HMC_API_URL: "http://hmc-cft-hearing-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - name: docmosis-enabled
          alias: IA_DOCMOSIS_ENABLED
        - name: em-stitching-enabled
          alias: IA_EM_STITCHING_ENABLED
        - name: system-username
          alias: IA_SYSTEM_USERNAME
        - name: system-password
          alias: IA_SYSTEM_PASSWORD
        - name: idam-client-id
          alias: IA_IDAM_CLIENT_ID
        - name: idam-secret
          alias: IA_IDAM_SECRET
        - name: s2s-secret
          alias: IA_S2S_SECRET
        - name: s2s-microservice
          alias: IA_S2S_MICROSERVICE
        - name: prof-ref-data-url
          alias: PROF_REF_DATA_URL
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
