---
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    DEPLOYMENT_FILTER_ENABLED: true
  keyVaults:
    ia:
      secrets:
        - name: docmosis-enabled
        - name: em-stitching-enabled
        - name: system-username
        - name: system-password
        - name: idam-client-id
        - name: idam-secret
        - name: s2s-secret
        - name: s2s-microservice
        - name: prof-ref-data-url
        - name: launch-darkly-sdk-key
        - name: ia-config-validator-secret
        - name: app-insights-connection-string
        - name: hmc-servicebus-connection-string
        - name: hmc-servicebus-shared-access-key-tf
        - name: ia-redis-connection-string
        - name: ia-redis-access-key
  redis:
    enabled: true
    serviceAccount:
      create: false
      name: "iac"
      automountServiceAccountToken: true
